### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Viktor-Beniukh**

### CODE REVIEW

**Comment by Viktor-Beniukh** [comment]
Screenshot 2022-12-16 141455
Screenshot 2022-12-16 205925
Screenshot 2022-12-16 210017
Screenshot 2022-12-16 210043
Screenshot 2022-12-16 210109
Screenshot 2022-12-16 210135
Screenshot 2022-12-16 210157
Screenshot 2022-12-16 210218
Screenshot 2022-12-16 210243
Screenshot 2022-12-16 210307

**Review by OleksandrPozden — CHANGES_REQUESTED** [review]
add this to comments in the pull request but remove repository
add a breakspace in the end of HTML files
image

**Comment by OleksandrPozden** [comment]
> add this to comments in the pull request but remove repository add a breakspace in the end of HTML files image

Sorry, I see images in the comments. So just delete from repository the image

**Review by OleksandrPozden — CHANGES_REQUESTED** [review]
make changes

**Comment by OleksandrPozden** [comment]
Also, add an option to cancel the action
image

**Pull request closed without merging**
